### ISSUE TITLE
Setting Schedule Interval

### ISSUE THREAD

**Issue by OluAgunloye** [danielgerlag/conductor#22]
How does one set the schedule interval? I've tried multiple formats available here: [https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=netframework-4.8#code-try-4](url)

and still no luck. What exactly am I doing wrong?

@danielgerlag @willsmith9182

**Comment by OluAgunloye** [comment]
Never mind, it's simply the difference of two `DateTime` objects.

**Comment by dammafra** [comment]
@OluAgunloye can you explain how it works? What should I put in the `Interval` property of the JSON Workflow definition?
